#!/bin/bash
# shellcheck disable=SC1091
source common.sh
resources=("inferenceservices" "inferencegraphs" "trainedmodels" "servingruntimes" "clusterstoragecontainers" "predictors" "localmodelnodegroups")
# Dependent resources authorino
resources+=("authconfigs" "authorinos" "authpolicies.kuadrant.io")
# Dependent resources NIM
resources+=("accounts.nim.opendatahub.io")
# Dependent resources llm-d
resources+=("llminferenceserviceconfigs" "llminferenceservices" "leaderworkersetoperators" "leaderworkersets" "inferencepools" "variantautoscalings.llmd.ai")
# Dependent resources MaaS
resources+=("ratelimitpolicies.kuadrant.io" "kuadrants.kuadrant.io" "tokenratelimitpolicies.kuadrant.io")
# Dependent resources KEDA
resources+=("scaledobjects.keda.sh" "scaledjobs.keda.sh" "triggerauthentications.keda.sh" "clustertriggerauthentications.keda.sh")

nslist=$(get_all_namespace "${resources[@]}")

run_k8sgather "$nslist" "${resources[@]}"
